version: "3"
services:
  ml:
    container_name: "ml"
    build: .
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    ipc: "host"
    network_mode: "host"
    command: "/bin/bash"
    tty: true
    stdin_open: true
    volumes:
      - .:/ml
    working_dir: /ml
