version: '3'
services:
  ml:
    container_name: 'ml'
    build: .
    image: ml:latest
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_PTRACE
    ipc: 'host'
    network_mode: 'host'
    command: '/bin/bash'
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
